import '../../styles/styles.scss'
import Head from 'next/head'

import { Lato } from 'next/font/google';
 
const lato = Lato({ 
  weight: ['100', '300', '400', '700', '900'],
  subsets: ['latin'] 
});

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>ITISDEV</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx global>{`
        html {
          font-family: ${lato.style.fontFamily};
        }
      `}</style>
      <Component {...pageProps} />
    </>

  )
}
