import '../../styles/styles.scss'
import Head from 'next/head'

import { Noto_Sans } from 'next/font/google';
import { Poppins } from 'next/font/google';

 
const noto_sans = Noto_Sans({ 
  weight: ['100', '300', '400', '700', '900'],
  subsets: ['latin'] 
});

const poppins = Poppins({ 
  weight: ['100', '300', '400', '700', '900'],
  subsets: ['latin']
});

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>ITISDEV</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx global>{`
        html {
          font-family: ${noto_sans.style.fontFamily};
        }

        .header {
          font-family: ${poppins.style.fontFamily};
        }
      `}</style>
      <Component {...pageProps} />
    </>

  )
}
